### ISSUE TITLE
www.hireable.me behaves differently than hireable.me (without www)

### ISSUE THREAD

**Issue by nguyenph88** [hiendv/hireable#12]
Will need to reconfig from the DNS site to make them work identically. Please assign this to me.

**Comment by nguyenph88** [comment]
Submitted the change on DNS site, wait for domain to propagate ...

**Comment by nguyenph88** [comment]
http://www.hireable.me
`; <<>> DiG 9.10.3-P4-Ubuntu <<>> www.hireable.me
www.hireable.me.        1798    IN      A       162.255.119.248`

http://hireable.me
`; <<>> DiG 9.10.3-P4-Ubuntu <<>> hireable.me
hireable.me.            1799    IN      A       162.255.119.248`

Done and closed!

**Comment by hiendv** [comment]
Thanks alot :gift:
